#include "LoginPage.h"
#include "ui_LoginPage.h" // Generated by uic
#include "ui/windows/CashatakMainWindow.h" // Added for navigation
#include <QDebug> // For potential error messages
#include <QMessageBox> // Added for error dialogs
#include "core/Database.h" // Added for database access
#include "core/Account.h" // Added for Account class
#include <iostream>
LoginPage::LoginPage(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::LoginPage)
{
    ui->setupUi(this);
    // Connect the GoToRegister button's clicked signal to its dedicated slot
    // connect(ui->pushButtonGoToRegister, &QPushButton::clicked, this, &LoginPage::on_pushButtonGoToRegister_clicked);
    // The login button click is handled by its own slot below
}

LoginPage::~LoginPage()
{
    delete ui;
}

void LoginPage::on_pushButtonLogin_clicked()
{
    // Get the entered username and password
    QString username = ui->lineEditUsername->text();
    QString password = ui->lineEditPassword->text();

    // Convert QString to std::string for Database API
    std::string usernameStr = username.toStdString();
    std::string passwordStr = password.toStdString();

    // Get database instance
    Database* db = Database::getInstance();
    
    std::cout << "usernameStr is " << usernameStr << std::endl;
    std::cout << "passwordStr is " << passwordStr << std::endl;
    // Try to get the account
    Account* account = db->getAccount(usernameStr);
    if (account) {
        // Hash the entered password and compare with stored hash
        std::string hashedPassword = Account::hashPassword(passwordStr);
        
        if (hashedPassword == account->getHashedPassword()) {
            // Find the main window to call its navigation slot
            CashatakMainWindow *mainWindow = nullptr;
            QWidget *ancestor = this;
            while(ancestor && !(mainWindow = qobject_cast<CashatakMainWindow*>(ancestor))) {
                ancestor = ancestor->parentWidget();
            }

            if (mainWindow) {
                mainWindow->navigateToHome();
            } else {
                qWarning() << "LoginPage: Could not find CashatakMainWindow instance to navigate.";
            }
        } else {
            // Password incorrect
            QMessageBox::warning(this, "Login Failed", "Incorrect password. Please try again.");
        }
    } else {
        // Account not found
        QMessageBox::warning(this, "Login Failed", "Account not found. Please check your username.");
    }
}

void LoginPage::on_pushButtonGoToRegister_clicked()
{
    // Find the main window to call its navigation slot
    CashatakMainWindow *mainWindow = nullptr;
    QWidget *ancestor = this;
    while(ancestor && !(mainWindow = qobject_cast<CashatakMainWindow*>(ancestor))) {
        ancestor = ancestor->parentWidget();
    }
    
    if (mainWindow) {
        mainWindow->navigateToRegister();
    } else {
        qWarning() << "LoginPage: Could not find CashatakMainWindow instance for register navigation.";
    }
    // Original line: emit navigateToRegisterRequested(); 
    // Replaced with direct navigation call
} 