#include "LoginPage.h"
#include "ui_LoginPage.h" // Generated by uic
#include "ui/windows/CashatakMainWindow.h" // Added for navigation
#include <QDebug> // For potential error messages

LoginPage::LoginPage(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::LoginPage)
{
    ui->setupUi(this);
    // Connect the GoToRegister button's clicked signal to its dedicated slot
    // connect(ui->pushButtonGoToRegister, &QPushButton::clicked, this, &LoginPage::on_pushButtonGoToRegister_clicked);
    // The login button click is handled by its own slot below
}

LoginPage::~LoginPage()
{
    delete ui;
}

void LoginPage::on_pushButtonLogin_clicked()
{
    // Find the main window to call its navigation slot
    CashatakMainWindow *mainWindow = nullptr;
    QWidget *ancestor = this;
    while(ancestor && !(mainWindow = qobject_cast<CashatakMainWindow*>(ancestor))) {
        ancestor = ancestor->parentWidget();
    }

    if (mainWindow) {
        mainWindow->navigateToHome();
    } else {
        // Handle error: MainWindow not found. This shouldn't happen in a typical setup.
        qWarning() << "LoginPage: Could not find CashatakMainWindow instance to navigate.";
    }
    // Original line: emit loginRequested(ui->lineEditUsername->text(), ui->lineEditPassword->text());
    // Removed as per request for simple redirect.
}

void LoginPage::on_pushButtonGoToRegister_clicked()
{
    // Find the main window to call its navigation slot
    CashatakMainWindow *mainWindow = nullptr;
    QWidget *ancestor = this;
    while(ancestor && !(mainWindow = qobject_cast<CashatakMainWindow*>(ancestor))) {
        ancestor = ancestor->parentWidget();
    }
    
    if (mainWindow) {
        mainWindow->navigateToRegister();
    } else {
        qWarning() << "LoginPage: Could not find CashatakMainWindow instance for register navigation.";
    }
    // Original line: emit navigateToRegisterRequested(); 
    // Replaced with direct navigation call
} 